### ISSUE TITLE
coinbase-vault-recovery - functional?

### ISSUE THREAD

**Issue by ianarman1** [maxweisspoker/coinbase-vault-recovery#1]
Hello,

Is this recovery tool still functional?

**Comment by maxweisspoker** [comment]
Sorry, I don't actually login and check Github that often, so I just now saw your issue.  I doubt this repo works any more -- Coinbase changes how their vault works many many years ago. However, if you happen to have an 5-10 year old vault that actually is a true multisig key, this script should still work.
